#!/usr/bin/env python

import sys
if len(sys.argv) > 1:
	f = open(sys.argv[1])
else:
	f = sys.stdin

num_fields = None
data = []
max_widths = None
for line in f:
	if not line.strip():
		data.append(line.strip())
		continue

	fields = line.split('\t')
	#print(fields)
	if not num_fields:
		num_fields = len(fields)
		max_widths = [0]*num_fields

	max_widths = [max(max_widths[i], len(fields[i])) for i in xrange(0, num_fields)]
	#print(max_widths)
	if len(fields) != num_fields:
		sys.stderr.write("%d fields in line instead of %d: %s\n" % (len(fields), num_fields, line))
	
	data.append(fields)

format_string = ""
for max_width in max_widths:
	format_string += "%" + str(max_width) + "s  "

for fields in data:
	if type(fields) is not type(list()):
		print(fields)
	else:
		#print(format_string)
		#print(format_string.count("%"), len(fields))
		#print(fields)
		print(format_string % tuple(fields))

	
