#!/usr/bin/env python3

import argparse
import os
import re

p = argparse.ArgumentParser()
p.add_argument("-t", "--num-threads", type=int, default=1)
p.add_argument("-m", "--model-type", choices=("WES", "WGS"), required=True)
p.add_argument("ref_fasta_path")
p.add_argument("bam_or_cram_path")
args = p.parse_args()

output_prefix = os.path.realpath(os.path.join(os.getcwd(), re.sub(".bam|.cram", "", os.path.basename(args.bam_or_cram_path))))

# see  https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md
c = (
    "docker run "
    "-v '/:/input' "
    "-v '/:/output' "
    "gcr.io/deepvariant-docker/deepvariant:0.8.0 "
    "/opt/deepvariant/bin/run_deepvariant "
    f"--ref=/input{os.path.realpath(os.path.abspath(args.ref_fasta_path))} "
    f"--model_type={args.model_type} "
    f"--reads=/input{os.path.realpath(os.path.abspath(args.bam_or_cram_path))} "
    f"--output_vcf=/output{output_prefix}.vcf.gz "
    f"--num_shards {args.num_threads} "
    )

print(c)
os.system(c)
