#!/usr/bin/env python3

import configargparse
import json
from pprint import pprint
from slacker import Slacker

parser = configargparse.ArgumentParser(default_config_files=["~/.slack_notifier"])
parser.add_argument("--slack-token", env_var="SLACK_TOKEN", help="Slack token to use for notifications")
parser.add_argument("--slack-channel", env_var="SLACK_CHANNEL", help="Slack channel to use for notifications")
parser.add_argument("message", nargs="+")
args, _ = parser.parse_known_args()

slack = Slacker(args.slack_token)

args.message = " ".join(args.message)
response = slack.chat.post_message(f"{args.slack_channel}", f"{args.message}", as_user=False, icon_emoji=":bell:", username="message-bot")

try:
    response_json = json.loads(response.raw)
except Exception as e:
    print(f"ERROR: Unable to parse response: {response.raw}: {e}")
else:
    if "ok" in response_json and response_json["ok"]:
        print(f"Sent slack message: '{args.message}'")
    else:
        print(f"ERROR: unable to send slack message: '{args.message}'")
        pprint(response_json)

